name = "full-stack-roadmap"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "docs/.vitepress/dist"

# Custom domain
routes = [
  { pattern = "f.tecfav.com", custom_domain = true }
]

[build]
command = "npm run docs:build"
